version: "3"
services:
  hub:
    image: selenium/hub:4.32
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.32
    shm_size: 2g
    depends_on:
      - hub
    ports:
      - "7900:7900" # VNC for Chrome
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=1
      - SE_VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080

  chrome-video:
    image: selenium/node-firefox:4.32
    depends_on:
      - chrome
    volumes:
      - ./videos:/videos
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_test_video.mp4